### ISSUE TITLE
Implement Reddit -> Teddit

### ISSUE THREAD

**Issue by magarenzo** [SygWave/reconstruct.py#1]

**Comment by sum35h** [comment]
Hi, I would like to work on this.

**Comment by magarenzo** [comment]
@sum35h Go for it! Assigned you, feel free to fork and submit a PR with your changes

This has now been implemented over at [reconstruct.js](https://github.com/SygWave/reconstruct.js), so feel free to follow that repo as a template

**Comment by magarenzo** [comment]
@sum35h I ended up implementing the feature myself, but thank you for your interest!
